apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: appxyz
  name: appxyz
spec:
  replicas: 4
  selector:
    matchLabels:
      app: appxyz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: appxyz
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
